### PR TITLE
Allow specifying a pattern for the tests to be run

### PR DESCRIPTION
**Pull request by rtoy**
When running on Android, it's quite a pain to select a subset of the tests using the selector.  Hence, allow a "pattern" URL query parameter to select which tests to be run.  The key is "pattern" and the value is a regular expression which is used to match the name of the test.  If the name matches, the test is selected.

### CODE REVIEW

**Comment by rtoy** [comment]
@bjornm PTAL.  I'm not very good with query strings and such, and I've probably made some mistakes or have some security issues with specifying a regex in the URL query string. Would appreciate some help on this.

But on the plus side, this works as I want it to when I use a pattern of "Oscillator".  The 3 oscillator tests are selected.

**Review by bjornm — COMMENTED** [review]
Thanks for the PR! URLSearchParams is good to use, helps avoid url parse errors.

User-defined regex:es is a potential denial of service if the user is also able to submit the strings to match against:

https://stackoverflow.com/questions/20928677/user-defined-regular-expression-security-concerns

This can cause the web page to hang. If you don't think you'll need fancy patterns, how about just checking for substring matching, e.g. 

```
if (test.name.indexOf(testPattern) !== -1) {
  // ...
}
```

**Comment by rtoy** [comment]
I doubt I'll need fancy patterns.  I don't expect to need to run, say, Biquad* and WaveShaper* at the same time.  It would be just Biquad or WaveShaper because I'd be just optimizing one node at a time.

**Review by bjornm — APPROVED** [review]
Perfect!

**Pull request merged**
